version: "3"

services:
    romm:
        image: rommapp/romm:latest
        container_name: romm
        restart: unless-stopped
        environment:
            - DB_HOST=romm-db
            - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
            - DB_USER=romm-user # Should match MARIADB_USER in mariadb
            - DB_PASSWD=rbbernabeu # Should match MARIADB_PASSWORD in mariadb
            - ROMM_AUTH_SECRET_KEY=631a8053aa69ecd85b909e19cd85642b0eadcc4a78151bee28393fd71afaa0a3 # Generate a key with `openssl rand -hex 32`
            - IGDB_CLIENT_ID=2bb8lpl56ah0t68umj940bihkcjdgh # Generate an ID and SECRET in IGDB
            - IGDB_CLIENT_SECRET=dr3sv4r3xxdgll7r0axac3h02funmq # https://api-docs.igdb.com/#account-creation
            - MOBYGAMES_API_KEY= # https://www.mobygames.com/info/api/
            - STEAMGRIDDB_API_KEY= # https://github.com/rommapp/romm/wiki/Generate-API-Keys#steamgriddb
        volumes:
            - /root/docker/romm/resources:/romm/resources
            - /root/docker/romm/redis:/redis-data
            - /mnt/ROMs:/romm/library/roms
            - /root/docker/romm/games/assets:/romm/assets
            - /root/docker/romm/games/config:/romm/config
        ports:
            - 8080:8080
        depends_on:
            romm-db:
                condition: service_healthy

    romm-db:
        image: mariadb:latest
        container_name: mariadb-romm
        restart: unless-stopped
        environment:
            - MARIADB_ROOT_PASSWORD=rbbernabeu # Use a unique, secure password
            - MARIADB_DATABASE=romm
            - MARIADB_USER=romm-user
            - MARIADB_PASSWORD=rbbernabeu
        ports:
            - 3309:3306
        volumes:
            - /root/docker/romm/mariadb:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 30s
            interval: 10s
            timeout: 5s
            retries: 5
